perturbation_nuplan:
  _target_: src.data_augmentation.state_perturbation.StatePerturbation
  _convert_: "all"

  dt: 0.1 # the time interval between trajectory points
  hist_len: 21
  low: [-1.0, -0.75, -0.35, -1, -0.5, -0.2, -0.1]
  high: [1.0, 0.75, 0.35, 1, 0.5, 0.2, 0.1]
  augment_prob: 0.5 # probability of applying data augmentation for training
  normalize: True
