hydra:
  run:
    dir: ${output_dir}
  output_subdir: ${output_dir}/code/hydra           # Store hydra's config breakdown here for debugging
  searchpath:                                       # Only <exp_dir> in these paths are discoverable
    - pkg://navsim.planning.script.config.common 

defaults:
  - default_common

# Cache parameters
cache:
  cache_path: ${oc.env:NAVSIM_EXP_ROOT}/metric_cache         
  use_cache_without_dataset: false                    
  force_feature_computation: false

output_dir: ${cache.cache_path}/metadata
navsim_log_path: ${oc.env:OPENSCENE_DATA_ROOT}/navsim_logs/${split} # path to log annotations